apiVersion: apps/v1
kind: Deployment
metadata:
  name: volvo-deployment
spec:
  selector:
    matchLabels:
      app: volvo
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: volvo
    spec:
      containers:
      - name: volvo
        image: hellovolvocr.azurecr.io/hello2022
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: hellovolvo
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
    selector:
        app: volvo


